### PR TITLE
Renamed Github action :tada:

### PR DESCRIPTION
**Pull request by fgauna12**

### CODE REVIEW

**Review by justin-vanwinkle — APPROVED** [review]
woot

**Comment by justin-vanwinkle** [comment]
Fixes [AB#17148](https://dev.azure.com/NebbiaDemo/70216d3a-d368-420e-8e43-7055406eb821/_workitems/edit/17148)

**Comment by desinole** [comment]
Closes: [AB#17149](https://dev.azure.com/NebbiaDemo/70216d3a-d368-420e-8e43-7055406eb821/_workitems/edit/17149)

**Comment by fgauna12** [comment]
I think it's done. Don't you think @desinole and @justin-vanwinkle?

**Pull request closed without merging**
